// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type Cliente struct {
	ID       int32  `json:"id"`
	Nombre   string `json:"nombre"`
	Apellido string `json:"apellido"`
	Usuario  string `json:"usuario"`
	Pass     string `json:"pass"`
	Email    string `json:"email"`
}

type Resena struct {
	ID          int32     `json:"id"`
	Titulo      string    `json:"titulo"`
	Descripcion string    `json:"descripcion"`
	Nota        int32     `json:"nota"`
	Fecha       time.Time `json:"fecha"`
	ClienteID   int32     `json:"cliente_id"`
}
