// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// Eliminamos el @Layout wrapper porque este componente ya se renderiza dentro de UserPage
func CrearEditarResena() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"grid-item\"><h2>Crear Reseña</h2><p id=\"cliente-detalle\"></p><form id=\"form-resena\" hx-post=\"/crear-resena\" hx-target=\"#mis-resenas-wrapper\" hx-swap=\"outerHTML\" hx-on::after-request=\"if(event.detail.successful) this.reset()\"><label>Título: <input type=\"text\" name=\"titulo\" required></label> <label>Descripción: <textarea name=\"descripcion\" required></textarea></label> <label>Nota (1-5): <input type=\"number\" name=\"nota\" min=\"1\" max=\"5\" required></label><div style=\"display:flex; gap:0.75rem; flex-wrap: wrap;\"><button type=\"submit\">Enviar Reseña</button> <button type=\"button\" id=\"btn-cancelar-edicion\" style=\"display:none;\" class=\"btn-secondary\">Cancelar edición</button></div></form><p id=\"mensaje-resena\"></p></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
